version: '3'
services:
  web:
    image: my_django_app
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - DJANGO_DEBUG=1
      # Другие переменные среды
    restart: always
